// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAT9HtFB12qYZAocKLrAP_zTgMkw0Uj-Y',
    appId: '1:1083238844569:web:201c505b85a4ee2d071008',
    messagingSenderId: '1083238844569',
    projectId: 'politix-app-6d070',
    authDomain: 'politix-app-6d070.firebaseapp.com',
    storageBucket: 'politix-app-6d070.firebasestorage.app',
    measurementId: 'G-ZW8V1SHKKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPFReIbu6Glo1FRT_PNmJ45hb0bSdzkw',
    appId: '1:1083238844569:android:8af656cf45af963c071008',
    messagingSenderId: '1083238844569',
    projectId: 'politix-app-6d070',
    storageBucket: 'politix-app-6d070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-bta3sJRQ2LmbPWqI0_10muTRCMZfDQ',
    appId: '1:1083238844569:ios:b2254d774b9ba612071008',
    messagingSenderId: '1083238844569',
    projectId: 'politix-app-6d070',
    storageBucket: 'politix-app-6d070.firebasestorage.app',
    iosBundleId: 'com.aymeric.appPolitix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-bta3sJRQ2LmbPWqI0_10muTRCMZfDQ',
    appId: '1:1083238844569:ios:b2254d774b9ba612071008',
    messagingSenderId: '1083238844569',
    projectId: 'politix-app-6d070',
    storageBucket: 'politix-app-6d070.firebasestorage.app',
    iosBundleId: 'com.aymeric.appPolitix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAT9HtFB12qYZAocKLrAP_zTgMkw0Uj-Y',
    appId: '1:1083238844569:web:fc387dfd74fb85db071008',
    messagingSenderId: '1083238844569',
    projectId: 'politix-app-6d070',
    authDomain: 'politix-app-6d070.firebaseapp.com',
    storageBucket: 'politix-app-6d070.firebasestorage.app',
    measurementId: 'G-M0L9TZK9C8',
  );
}
